<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="2">

  <testsuite name="test"
    errors="1" failures="0" hostname="" id="" package="test" skipped="1"
    tests="2" time="0.01200" timestamp="Fri, 01 Jun 2018 12:11:15 GMT">
  
    <testcase name="login tests" time="0.01200" assertions="0">
    </testcase>
      <system-err>
          Error while running [Test / login tests]:

  ReferenceError: NODE_ENV is not defined
    at Object.loginTests [as login tests] (D:/Users/Wadie/Projects/quiz-app-backoffice/test/e2e/specs/test.js:9:17)
    at Module.call (D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\nightwatch\lib\runner\module.js:62:34)
    at D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\q\q.js:816:13)
    at D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\q\q.js:570:49
    at runSingle (D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\q\q.js:137:13)
    at flush (D:\Users\Wadie\Projects\quiz-app-backoffice\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
      </system-err>
  
  
    
    <testcase
      name="after auth tests">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
